config/routes.rb
RailsFrance::Application.routes.draw do
  filter :pagination

  # Root
  root :to => "home#index"

  # Devise
  devise_for :users, :path => 'compte',
    :path_names => { :sign_in => 'connexion', :sign_out => 'deconnexion',
      :sign_up => 'inscription', :password => 'mot-de-passe' }

  # User
  resources :membres, :controller => :users, :as => :users, :only => [:index, :show]

  match 'preview' => 'content#preview'

  # Map
  resources :map, :only => [:index] do
    collection do
      get :users
      get :jobs
      get :events
    end
  end

  # Jobs
  resources :jobs do
    collection do
      get :preview
      get :confirm
    end
  end

  match '/jobs/validate/:token' => 'jobs#validate', :as => 'validate_job'
  match '/jobs/edit/:token' => 'jobs#edit', :as => 'edit_job'

  # Questions & Answers
  resources :questions do
    get :vote, :on => :member
    get :autocomplete_tag_name, :on => :collection
    resources :answers, :only => [:create] do
      get :vote, :on => :member
      get :accept, :on => :member
    end
  end

  # Tags
  resources :tags, :only => [:index]

  # Events
  resources :evenements, :controller => :events, :as => :events do
    get :attend, :on => :member
    get :unattend, :on => :member
    resources :comments, :only => [:create]
  end

  # Resources
  resources :ressources, :controller => :resources, :as => :resources, :only => [:index]

  # Contacts
  resources :contacts do
    post :send_email, :on => :collection
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  extend FriendlyId
  include Addresseable

  image_accessor :logo
  attr_accessor :contracts_error

  friendly_id :title, :use => :slugged

  validates_presence_of :company, :street, :city, :description, :postal_code
  validates_format_of :url, :with => /^(#{URI::regexp(%w(http https))})$/, :allow_blank => true
  validates :email, :presence => true, :format => {:with => Devise::email_regexp}
  validates :title, :presence => true, :uniqueness => true, :length => { :maximum => 100 }
  validate :validate_contracts

  paginates_per 10

  state_machine :initial => :pending do
    after_transition :pending => :confirmed do |job, trans|
      job.generate_token
    end

    after_transition :confirmed => :activated do |job, trans|
      job.send :notify_observers, :after_activation
    end

    event :confirm do
      transition :pending => :confirmed
    end

    event :activate do
      transition :confirmed => :activated
    end
  end

  def to_s; title end

  def contracts
    {cdi: cdi, cdd: cdd, freelance: freelance, internship: internship}.delete_if {|k,v| !v}.keys
  end

  def generate_token
    update_attribute(:token, SecureRandom.hex(13))
  end

  private
  def validate_contracts
    errors.add(:contracts_error, "Selectionner au moins un type de contrat") unless (cdd or cdi or freelance or internship)
  end

end

app/models/search/job.rb
class Search::Job < BasicActiveModel
  attr_accessor :freelance, :cdi, :cdd, :internship, :remote

  def execute
    jobs = Job.with_state(:activated)

    where = [:freelance, :cdi, :cdd, :internship].inject([]) do |a,b|
      a << "#{b} = 't'" if send(b)
      a
    end.join(' OR ')

    jobs = jobs.where(where) unless where.blank?
    jobs = jobs.order('created_at DESC')
    jobs
  end

  def initialize(attributes)
    attributes = attributes.each_pair {|k,v| attributes[k] = (v.to_i == 1 ? true : false)}
    super(attributes)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include Messages

  before_filter :load_from_session, :only => [:preview, :confirm]
  before_filter :load_from_params, :only => [:show, :update]

  respond_to :html, :atom

  def index
    params[:search_job] ||= {}
    @search = Search::Job.new params[:search_job]
    @jobs = @search.execute.page params[:page]
    respond_with @jobs
  end

  def new
    @job = Job.new
  end

  def show
    unless @job.activated?
      error(:job_not_activated)
      redirect_to :root
    end
  end

  def create
    @job = Job.new params[:job]

    if verify_recaptcha(model: @job, message: I18n.t('recaptcha.errors.verification_failed')) && @job.save
      session[:job_id] = @job.id
      redirect_to preview_jobs_path
    else
      error(:form_not_valid, {now: true})
      render(:new) and return
    end
  end

  def preview
    render :show
  end

  def edit
    redirect_to :root and return unless
      @job = Job.with_state(:activated).where(:token => params[:token]).first
    render :new
  end

  def update
    if @job.update_attributes(params[:job])
      notice(:job_updated)
      redirect_to(@job)
    else
      error(:job_not_updated, {now: true})
      render :new
    end
  end

  def confirm
    @job.confirm!
    ContactMailer.confirm_job(@job).deliver
    session[:job_id] = nil
    notice(:job_confirmation) and redirect_to :root
  end

  def validate
    redirect_to :root and return unless @job = Job.with_state(:confirmed).where(:token => params[:token]).first
    @job.activate!
    ContactMailer.valid_job(@job).deliver
    notice(:job_validated) and redirect_to job_path(@job)
  end

  private
  def load_from_session
    error(:job_unknown) and redirect_to :root unless session[:job_id]
    @job = Job.find session[:job_id]
  end

  def load_from_params
    @job = Job.find params[:id]
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def link_to_company job
    return job.company unless job.url.present?
    link_to job.company, job.url, "data-skip-pjax" => "true", :target => "_blank"
  end

  def format_contracts contracts
    contracts.map { |v| Job.human_attribute_name(v.to_sym) }.join(', ')
  end
end

app/views/jobs/_form.html.haml
= simple_form_for @job , :html => {:multipart => true, :class => "jobForm"} do |f|
  %fieldset
    %legend= "Poster votre annonce"
    .jobFormLeft
      = f.input :company, :autofocus => "autofocus"
      = f.input :email, :label => "Email <span style='font-size:11px;'>(sera utilisé pour gérer votre annonce et vous faire contacter par un candidat)</span>".html_safe unless action_name == 'edit'
      = f.input :url, :placeholder => "http://www.railsfrance.org"
      #jobFormType
        %label
          Type de contrat
        %ul
          %li
            = f.input :cdi
            = f.input :cdd
          %li
            = f.input :freelance
            = f.input :internship
      - unless @job.errors[:contracts_error].empty?
        .textError
          = @job.errors[:contracts_error].first
    .jobFormRight
      = f.input :title
      = f.input :street
      = f.input :city
      = f.input :postal_code
    = f.input :description, :as => :wysiwyg, :wrapper_html => { :class => "clear" }
    %p.markdownLink La syntaxe #{link_to "Markdown", "http://github.github.com/github-flavored-markdown/","data-skip-pjax" => "true", :target => "_blank", :id => "markdownHelp"} est supportée
    .jobFormLeft
      %div
        %label
          Logo de votre entreprise
          %span{:style => 'font-size:11px;'}
            (sera redimensionné en 200x100px)
        %div
          Envoyer un fichier
        = f.input :logo, :as => :file, :label => false
      %div
        %label
          Ou renseigner une url
        = f.text_field :logo_url
  
        = image_tag @job.logo.thumb('200x100').url if @job.logo_uid
        = f.hidden_field :retained_logo
    .jobFormRight
      = recaptcha_tags 
      - if @job.errors[:base].any?
        .textError
          = @job.errors[:base].join("<br/>")
    .block.center
      = f.button :submit, id: 'job_form_submit'

app/views/jobs/_job.html.haml
- set_meta_tags :title => "Toutes les offres d'emplois disponibles en Ruby On Rails"
%li.theContentListLi
  %aside
    = l(job.created_at, :format => :tiny)
  %article
    = image_tag (job.logo_uid.present? ? job.logo.thumb('56x').url : image_path('jobs/job_default.png')), :width => 56
    %h2.theContentListTitle
      = link_to job.title, job_path(job), :class => "theContentListTitle"
    .jobDescription
      = truncate(sanitize(job.description), length: 200).html_safe
    .informationsBlock
      .jobCompany
        Employeur :
        %span
          = link_to_company job
      .jobCity
        Lieu :
        %span
          = job.city
      .jobType
        Type:
        %span
          = format_contracts job.contracts

app/views/jobs/_sort.html.haml
#jobsSort
  = simple_form_for @search, :url => jobs_path, :html => {:id => 'search',:method => :get} do |f|
    %div.input
      = f.label :cdi
      = f.input :cdi, :as => :boolean, :label => false, :wrapper => false
    %div.input
      = f.label :cdd
      = f.input :cdd, :as => :boolean, :label => false, :wrapper => false
    %div.input
      = f.label :freelance
      = f.input :freelance, :as => :boolean, :label => false, :wrapper => false
    %div.input
      = f.label :internship, "Stage"
      = f.input :internship, :as => :boolean, :label => false, :wrapper => false

app/views/jobs/confirm.html.haml
= image_tag @job.logo.url

app/views/jobs/index.html.haml
- feed("RailsFrance » Jobs", jobs_url(:atom))
%section.worldMap
  %header#sectionHeader
    %hgroup.jobsHeader
      %h1
        %span 
          Les
        JOBS
  %nav#secondaryNav
    %div#secondaryNavContainer
      = simple_form_for @search, :url => jobs_path, :html => {:id => 'search',:method => :get} do |f|
        %ul
          %li
            = f.label :cdi
            = f.input :cdi, :as => :boolean, :label => false, :wrapper => false
          %li.shadow
            = f.label :cdd
            = f.input :cdd, :as => :boolean, :label => false, :wrapper => false
          %li.shadow
            = f.label :freelance
            = f.input :freelance, :as => :boolean, :label => false, :wrapper => false
          %li.shadow
            = f.label :internship, "Stage"
            = f.input :internship, :as => :boolean, :label => false, :wrapper => false
          %li.shadow
            = link_to "Déposer une offre", new_job_path, "data-skip-pjax" => true, :class => "navButton add"
          %li
            = link_to "RSS", jobs_url(:atom), "data-skip-pjax" => true, :class => "navButton rss"
  .theContent
    - if @jobs.empty?
      %p.noAnwser Aucune offre d'emploi pour le moment
    - else
      %ul.jobList.theContentList
        = render @jobs
      .pagination
        = paginate @jobs

app/views/jobs/new.html.haml
- set_meta_tags :title => "Poster votre annonce/offre d'emploi sur Railsfrance.org"
%section.worldMap
  %header#sectionHeader
    %hgroup.jobsHeader
      %h1
        %span 
          Les
        JOBS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %ul
        %li
          = link_to "Retour aux annonces", jobs_path, :class => "navButton back"
  .theContent
    = render 'form'
    = render 'markdown/markdown'

app/views/jobs/show.html.haml
- set_meta_tags :title => "Offre d'emploi : #{@job.title}", :description => @job.description.truncate(150)
%section.worldMap
  %header#sectionHeader
    %hgroup.jobsHeader
      %h1
        %span 
          Les
        JOBS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %ul
        %li
          = link_to "Retour aux annonces", jobs_path, :class => "navButton back"
        - if params[:action] == "preview"
          %li
            = link_to "Confirmer", confirm_jobs_path, "data-skip-pjax" => true, :class => "navButton"
  .theContent
    %article#theJob
      = image_tag (@job.logo_uid.present? ? @job.logo.thumb('56x').url : image_path('jobs/job_default.png')), :width => 56
      #theJobDate
        = l(@job.created_at, :format => :tiny)
      %hgroup
        %h1
          = @job.title
      #theJobInformations
        .jobCompany
          Employeur :
          %span
            = link_to_company @job
        .jobCity
          Lieu :
          %span
            = @job.city
        .jobType
          Type:
          %span
            = format_contracts @job.contracts
      #theJobDescription.userMarkdown
        = markdown @job.description
      #theJobApply
        %p
          Vous souhaitez postuler pour ce poste ?
        %p
          Envoyer un email à
          = link_to @job.email, "mailto:#{@job.email}", "data-skip-pjax" => true
      - if params[:action] == "preview"
        .center
          = link_to "Confirmer", confirm_jobs_path, "data-skip-pjax" => true, :class => "button"
        
      
    