config/routes.rb
RailsFrance::Application.routes.draw do
  filter :pagination

  # Root
  root :to => "home#index"

  # Devise
  devise_for :users, :path => 'compte',
    :path_names => { :sign_in => 'connexion', :sign_out => 'deconnexion',
      :sign_up => 'inscription', :password => 'mot-de-passe' }

  # User
  resources :membres, :controller => :users, :as => :users, :only => [:index, :show]

  match 'preview' => 'content#preview'

  # Map
  resources :map, :only => [:index] do
    collection do
      get :users
      get :jobs
      get :events
    end
  end

  # Jobs
  resources :jobs do
    collection do
      get :preview
      get :confirm
    end
  end

  match '/jobs/validate/:token' => 'jobs#validate', :as => 'validate_job'
  match '/jobs/edit/:token' => 'jobs#edit', :as => 'edit_job'

  # Questions & Answers
  resources :questions do
    get :vote, :on => :member
    get :autocomplete_tag_name, :on => :collection
    resources :answers, :only => [:create] do
      get :vote, :on => :member
      get :accept, :on => :member
    end
  end

  # Tags
  resources :tags, :only => [:index]

  # Events
  resources :evenements, :controller => :events, :as => :events do
    get :attend, :on => :member
    get :unattend, :on => :member
    resources :comments, :only => [:create]
  end

  # Resources
  resources :ressources, :controller => :resources, :as => :resources, :only => [:index]

  # Contacts
  resources :contacts do
    post :send_email, :on => :collection
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @presenter = Home::IndexPresenter.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
  MARKERS = %w[jobs users events]

  def map_markers(presenter)
    MARKERS.inject([]) do |container, object|
      presenter.send(object).each do |o|
        container << {title: (o.respond_to?('title') ? o.title : o.username), lat: o.latitude, lng: o.longitude, icon: "#{image_path('map/' + o.class.to_s.downcase + 's.png')}", link: url_for(o)}
      end
      container
    end.to_json
  end
end

app/views/home/index.html.haml
- set_meta_tags :title => "RailsFrance.org | La communauté francophone des utilisateurs de Ruby On Rails", 
:description => "Questions, offres d'emplois, événements, Ruby On Rails, France"

%section#homeSection.worldMap
  %header#homeHeader
    %ul
      %li
        = link_to resources_path(:anchor => "discover"), "data-skip-pjax" => true, :id => "discoverRuby" do
          %span
            Découvrir
          %br
          Ruby on Rails     
      %li
        = link_to resources_path(:anchor => "download"), "data-skip-pjax" => true, :id => "downloadRuby" do
          %span
            Télécharger
          %br
          Ruby on Rails
      %li
        = link_to resources_path(:anchor => "learn"), "data-skip-pjax" => true, :id => "learnRuby" do
          %span
            Apprendre
          %br
          à développer
      %li
        = link_to resources_path(:anchor => "community"), "data-skip-pjax" => true, :id => "contributeRuby" do
          %span
            Contribuer
          %br
          à la communauté
  #homeHgroup
    = link_to "Rails", "http://rubyonrails.org/","data-skip-pjax" => true, :target => "_blank"
    %div
      %h1
        Bienvenue sur le portail francophone de la communauté Ruby on Rails
      %p
        Vous trouverez ici toutes les ressources nécessaires pour débuter avec Ruby on Rails et partager avec sa communauté française.
  #homeContent
    #homeEvents.homeContent
      %h2
        Les évènements Rails
      %ul
        - @presenter.recent_events.each do |event|
          %li
            %article
              %h3
                = link_to truncate(event.title, length: 35), event_path(event), "data-skip-pjax" => true
              %p
                = truncate(sanitize(event.description), length: 100).html_safe
      = link_to "Voir tous les évènements", events_path, "data-skip-pjax" => true, :class => "smallButton"
    #homeJobs.homeContent
      %h2
        Les Jobs Rails
      %ul
        - @presenter.recent_jobs.each do |job|
          %li
            %article
              %h3
                = link_to truncate(job.title, length: 35), job_path(job), "data-skip-pjax" => true
              %p
                = truncate(sanitize(job.description), length: 100).html_safe 
      = link_to "Voir tous les Jobs", jobs_path, "data-skip-pjax" => true, :class => "smallButton"
    #homeTweets.homeContent
      %h2
        Les Derniers Tweets
      %ul
        - @presenter.recent_tweet.each do |tweet|
          %li
            %p
              = tweet['text']
              %br
              %span= "{ Il y a #{distance_of_time_in_words tweet['created_at'].to_time, Time.now} }"
      = link_to  "Accéder au Twitter", "http://twitter.com/#{Settings.twitter.account}","data-skip-pjax" => true, :target => "_blank", :class => "smallButton"
    %h4
      Les projets sur les rails
    %ul#railsProjectSlider
      - @presenter.rails_projects.each do |project|
        %li
          = link_to image_tag("home/caroussel/#{project[:img]}"), project[:link], :title => project[:title], :target =>"_blank", 'data-skip-pjax' => true
    