config/routes.rb
RailsFrance::Application.routes.draw do
  filter :pagination

  # Root
  root :to => "home#index"

  # Devise
  devise_for :users, :path => 'compte',
    :path_names => { :sign_in => 'connexion', :sign_out => 'deconnexion',
      :sign_up => 'inscription', :password => 'mot-de-passe' }

  # User
  resources :membres, :controller => :users, :as => :users, :only => [:index, :show]

  match 'preview' => 'content#preview'

  # Map
  resources :map, :only => [:index] do
    collection do
      get :users
      get :jobs
      get :events
    end
  end

  # Jobs
  resources :jobs do
    collection do
      get :preview
      get :confirm
    end
  end

  match '/jobs/validate/:token' => 'jobs#validate', :as => 'validate_job'
  match '/jobs/edit/:token' => 'jobs#edit', :as => 'edit_job'

  # Questions & Answers
  resources :questions do
    get :vote, :on => :member
    get :autocomplete_tag_name, :on => :collection
    resources :answers, :only => [:create] do
      get :vote, :on => :member
      get :accept, :on => :member
    end
  end

  # Tags
  resources :tags, :only => [:index]

  # Events
  resources :evenements, :controller => :events, :as => :events do
    get :attend, :on => :member
    get :unattend, :on => :member
    resources :comments, :only => [:create]
  end

  # Resources
  resources :ressources, :controller => :resources, :as => :resources, :only => [:index]

  # Contacts
  resources :contacts do
    post :send_email, :on => :collection
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  include Addresseable

  default_scope :order => 'date DESC'
  belongs_to :user, :counter_cache => :events_count

  friendly_id :title, :use => :slugged

  paginates_per 10

  attr_accessible :title, :description, :city, :postal_code,
  :street, :date, :website, :latitude, :longitude

  delegate :page, :to => :comments, :prefix => true, :allow_nil => true
  delegate :username, :to => :user, :prefix => true, :allow_nil => true
  delegate :gravatar_url, :to => :user, :prefix => true, :allow_nil => true

  validates_presence_of :city, :street, :postal_code, :user
  validates :title, :presence => true, :length => { :maximum => 100 }
  validates :description, :presence => true, :length => { :maximum => 500 }
  validates_format_of :website, :with => /^(#{URI::regexp(%w(http https))})$/, :allow_blank => true
  validates :date, :date => { :after => Time.now, :message => I18n.t('event.error.date') }, :presence => true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include PreLoginParams

  keep_params :event, :only => [:create]
  load_params :event, :only => [:new]

  load_and_authorize_resource :event, :only => [:show, :edit]
  load_and_authorize_resource :through => :current_user, :only => [:create, :update]

  respond_to :html, :atom

  def index
    @presenter = Events::IndexPresenter.new
    @events = Event.page params[:page]
    respond_with @events
  end

  def create
    if @event.save
      redirect_to @event, :notice => t('event.flash.created')
    else
      render :new
    end
  end

  def update
    if @event.update_attributes params[:event]
      redirect_to @event, :notice => t('event.flash.updated')
    else
      render :edit
    end
  end
end

app/views/events/_event.html.haml
%li.theContentListLi
  %aside{:class => event.date > Time.now ? "blue" : "red"}
    = l(event.date, :format => :tiny)
  %article
    %h2.theContentListTitle
      = link_to truncate(event.title, :length => 50), event, :class => "theContentListTitle"
    .eventDescription
      = truncate(sanitize(event.description), length: 200).html_safe
    .informationsBlock
      .eventCity
        Ville:
        %span
          = event.city
      .eventAddress
        Adresse :
        %span
          = event.street
      .eventHour
        Heure de l'événement :
        %span
          = l(event.date, :format => :short)
      

app/views/events/_form.html.haml
= f.input :title, :autofocus => "autofocus"
= f.input :description, :as => :wysiwyg
%p.markdownLink La syntaxe #{link_to "Markdown", "http://github.github.com/github-flavored-markdown/","data-skip-pjax" => "true", :target => "_blank", :id => "markdownHelp"} est supportée
#eventFormLeft
  = f.input :street
  = f.input :postal_code
  = f.input :city
#eventFormRight
  = f.input :website, :placeholder => "http://www.railsfrance.org"
  = f.input :date, :as => :string
  %br
  %br
  = f.button :submit

app/views/events/edit.html.haml
%section.worldMap
  %header#sectionHeader
    %hgroup.eventHeader
      %h1
        %span 
          LES
        ÉVÉNEMENTS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %ul
        %li
          = link_to "Retour aux événements", events_path, :class => "navButton back"
  .theContent
    = simple_form_for @event, :html => { :class => "eventForm"} do |form|
      %fieldset
        %legend Editez votre événement
        = render 'form', :f => form

app/views/events/index.html.haml
- set_meta_tags :title => "Tous les événements à venir"
- feed("RailsFrance » Evénéments", events_url(:atom))
%section.worldMap
  %header#sectionHeader
    %hgroup.eventHeader
      %h1
        %span 
          LES
        ÉVÉNEMENTS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %h2 
        Nombre d'événements à venir :
      %div#eventNumber
        = @presenter.incoming_events
      %ul
        %li
          = link_to "Créer un événement", new_event_path, :id => "addEvent", :class => "navButton add"
        %li
          = link_to "RSS", events_url(:atom), "data-skip-pjax" => true, :class => "navButton rss"
  .theContent
    %ul.eventList.theContentList
      = render @events
    .pagination
      = paginate @events

app/views/events/new.html.haml
- set_meta_tags :title => "Postez votre événement!"
%section.worldMap
  %header#sectionHeader
    %hgroup.eventHeader
      %h1
        %span 
          LES
        ÉVÉNEMENTS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %ul
        %li
          = link_to "Retour aux événements", events_path, :class => "navButton back"
  .theContent
    = simple_form_for @event , :url => events_path, :html => { :class => "eventForm", :method => :post } do |form|
      %fieldset
        %legend Créer votre événement
        = render 'form', :f => form
        = render 'markdown/markdown'

app/views/events/show.html.haml
%section.worldMap
  %header#sectionHeader
    %hgroup.eventHeader
      %h1
        %span 
          LES
        ÉVÉNEMENTS
  %nav#secondaryNav
    %div#secondaryNavContainer
      %ul
        %li
          = link_to "Retour aux événements", events_path, :class => "navButton back"
        - if can? :update, @event
          %li
            = link_to "Editer", edit_event_path(@event), :class => "navButton"
  .theContent
    %article#theEvent
      %hgroup
        %h1
          = @event.title
      #theEventInformation
        #theEventAddress
          Adresse :
          %span
            = link_to "#{@event.street} #{@event.postal_code} #{@event.city}", "http://maps.google.com/maps?q=#{CGI::escape([@event.street, @event.postal_code, @event.city].compact.join(' '))}","data-skip-pjax" => true, :target => "_blank"
        #theEventDate
          Date :
          %span
            = l(@event.date, :format => :tiny)
        #theEventHour
          Heure :
          %span
            = l(@event.date, :format => :short)
    #theEventDescription.userMarkdown
      = markdown @event.description
      %p
        = link_to @event.website, @event.website,"data-skip-pjax" => true, :target => "_blank"
   
      