config/routes.rb
RailsFrance::Application.routes.draw do
  filter :pagination

  # Root
  root :to => "home#index"

  # Devise
  devise_for :users, :path => 'compte',
    :path_names => { :sign_in => 'connexion', :sign_out => 'deconnexion',
      :sign_up => 'inscription', :password => 'mot-de-passe' }

  # User
  resources :membres, :controller => :users, :as => :users, :only => [:index, :show]

  match 'preview' => 'content#preview'

  # Map
  resources :map, :only => [:index] do
    collection do
      get :users
      get :jobs
      get :events
    end
  end

  # Jobs
  resources :jobs do
    collection do
      get :preview
      get :confirm
    end
  end

  match '/jobs/validate/:token' => 'jobs#validate', :as => 'validate_job'
  match '/jobs/edit/:token' => 'jobs#edit', :as => 'edit_job'

  # Questions & Answers
  resources :questions do
    get :vote, :on => :member
    get :autocomplete_tag_name, :on => :collection
    resources :answers, :only => [:create] do
      get :vote, :on => :member
      get :accept, :on => :member
    end
  end

  # Tags
  resources :tags, :only => [:index]

  # Events
  resources :evenements, :controller => :events, :as => :events do
    get :attend, :on => :member
    get :unattend, :on => :member
    resources :comments, :only => [:create]
  end

  # Resources
  resources :ressources, :controller => :resources, :as => :resources, :only => [:index]

  # Contacts
  resources :contacts do
    post :send_email, :on => :collection
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable

  belongs_to :user, :counter_cache => :answers_count
  belongs_to :question, :counter_cache => :answers_count

  paginates_per 5
  make_voteable

  delegate :user, :to => :question, :prefix => true, :allow_nil => true
  delegate :username, :to => :user, :prefix => true, :allow_nil => true
  delegate :accepted_answer, :to => :question, :prefix => true, :allow_nil => true
  delegate :title, :to => :question, :prefix => true, :allow_nil => true

  attr_accessible :question, :description

  validates_presence_of :user, :question, :description

  def accepteable_by?(user)
    (user == self.question_user) && (user != self.user) && self.question_accepted_answer.nil?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include PreLoginParams

  keep_params :answer, :only => [:create]

  load_and_authorize_resource :only => [:vote, :accept]
  load_and_authorize_resource :question

  def create
    if current_user.answers.create(params[:answer].merge(:question => @question))
      redirect_to @question, :notice => t('answer.flash.created')
    else
      @answers = @question.answers_page(params[:page])
      render 'questions/show'
    end
  end

  def vote
    flash[:notice] = @answer.vote(current_user, params[:vote])
    redirect_to @question
  end

  def accept
    if @question == @answer.question
      @question.accepted_answer = @answer
      flash[:notice] = t('answer.flash.answered') if @question.save
    end
    redirect_to @question
  end
end

app/views/answers/_answer.html.haml
%li{:class => ((answer == answer.question_accepted_answer) ? "theContentListLi validated" : "theContentListLi")}
  %aside.votesContainer
    - if user_signed_in?
      - if can? :vote, answer
        = link_to "Vote up", vote_question_answer_path(answer.question, answer, :vote => "up"), :class => "voteUp", "data-skip-pjax" => "true"
        .votesNumber
          #{answer.votes}
        = link_to "Vote down", vote_question_answer_path(answer.question, answer, :vote => "down"), :class => "voteDown", "data-skip-pjax" => "true"
      - else
        = link_to "Vote up", "#", :class => "voteUp disabled"
        .votesNumber
          #{answer.votes}
        = link_to "Vote down", "#", :class => "voteDown disabled"
      - if can? :accept, answer
        = link_to "Accepter la réponse", accept_question_answer_path(answer.question, answer),:class => "answerAccept", "data-skip-pjax" => "true"
    - else
      = link_to "Vote up", "#", :class => "voteUp disabled"
      .votesNumber
        #{answer.votes}
      = link_to "Vote down", "#", :class => "voteDown disabled"
  %article
    = markdown answer.description
    .postHourUser
      %span
        Postée il y a #{distance_of_time_in_words_to_now(answer.created_at)} 
        par #{link_to answer.user.username, user_path(answer.user)} 
        = image_tag answer.user.gravatar_url

    